# Generated by Django 4.2.2 on 2023-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="artist",
            fields=[
                ("artist_id", models.AutoField(primary_key=True, serialize=False)),
                ("artist_name", models.CharField(max_length=30)),
                ("song_name", models.CharField(max_length=30)),
                ("songaudio_file", models.FileField(upload_to="audio/")),
                ("duration", models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("song_id", models.AutoField(primary_key=True, serialize=False)),
                ("song_artist", models.CharField(max_length=30)),
                ("song_duration", models.DecimalField(decimal_places=2, max_digits=5)),
                ("popularity", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("mobile_no", models.BigIntegerField()),
                ("email", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=50)),
                ("liked_songs", models.ManyToManyField(to="new_app.song")),
            ],
        ),
    ]
