# Generated by Django 4.2.3 on 2023-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(default='Test Song', max_length=30),
            preserve_default=False,
        ),
    ]
