# Generated by Django 4.2.2 on 2023-07-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0004_rename_duration_artist_duration_str"),
    ]

    operations = []
