# Generated by Django 4.2.3 on 2023-07-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_merge_0002_song_song_name_0005_auto_20230710_0047'),
    ]

    operations = [
    ]
