# Generated by Django 4.2.2 on 2023-07-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0007_auto_20230710_1958"),
    ]

    operations = []
