# Generated by Django 4.2.2 on 2023-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0011_remove_song_song_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="song_duration",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
