# Generated by Django 4.2.2 on 2023-07-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0012_song_song_duration"),
    ]

    operations = []
