# Generated by Django 4.2.2 on 2023-07-13 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0013_auto_20230713_2232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="songaudio_file",
        ),
        migrations.AddField(
            model_name="song",
            name="songaudio_file_urn",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_duration",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
