# Generated by Django 4.2.2 on 2023-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0014_remove_song_songaudio_file_song_songaudio_file_urn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="song_duration",
        ),
    ]
