# Generated by Django 4.2.2 on 2023-07-31 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0015_remove_song_song_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="liked_songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_songs", models.ManyToManyField(to="new_app.song")),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_id_ref",
                        to="new_app.user",
                    ),
                ),
            ],
        ),
    ]
